name: Leaflow Auto Checkin

on:
  schedule:
    - cron: '0 1 * * *' # 每天UTC时间01:00运行（北京时间09:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run auto checkin
      env:
        LEAFLOW_ACCOUNTS: ${{ secrets.LEAFLOW_ACCOUNTS }}
        LEAFLOW_EMAIL: ${{ secrets.LEAFLOW_EMAIL }}
        LEAFLOW_PASSWORD: ${{ secrets.LEAFLOW_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_ACTIONS: true
      run: |
        python leaflow_checkin.py
